# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  ddd-microservice:
    image: ddd-microservice
    container_name: ddd-microservice
    build:
      context: .
      dockerfile: DDDMicroservice/PETRA.API/Dockerfile
    ports:
      - 5194:5194
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - db
      - rabbitmq
  db:
   image: postgres:14.1-alpine
   restart: always
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   ports:
     - '5432:5432'
   volumes: 
     - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
